name: Publish patch
on: workflow_dispatch

jobs:
  release_patch:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'release-')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Releasing...
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn publish:patch --yes
          CURRENT_BRANCH=`git branch --show-current`
          git checkout main
          git merge $CURRENT_BRANCH
          git push origin main
